name: aws-iam-authenticator

on:
  push:
  workflow_dispatch:

jobs:
  aws-iam-authenticator:
    runs-on: ubuntu-latest
    steps:
      - name: install aws-iam-authenticator
        run: |
          wget https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.2/aws-iam-authenticator_0.5.2_linux_amd64 \
            -O /usr/local/bin/aws-iam-authenticator
      - name: test installation
        run: |
          aws-iam-authenticator version
          aws-iam-authenticator help
