name: https://chenrui.dev site check

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  site-check:
    runs-on: ubuntu-latest
    steps:
      - name: test site
        run: wget https://chenrui.dev
