name: aws credentials flow

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Write into file
        id: write_file
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'myTemporaryFile.txt'
          encodedString: ${{ secrets.AWS_CREDENTIALS_FILE_BASE64 }}

      - name: Use the output
        run: |
          ls ${{ steps.write_file.outputs.filePath }}
          cat ${{ steps.write_file.outputs.filePath }}
