name: node-v14-test

on: [push, pull_request]

jobs:
  label:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - run: |
          npm --version
          node --version
          grunt --version
