name: perl-test

on:
  push:
    branches:
      - 'perl-test'
  workflow_dispatch:

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: Install perl dependencies for html_opt.pl
        run: |
          # sudo apt-get install -y libdb5.1 libberkeleydb-perl
          sudo apt-get jq ant lbzip2 libglib2.0-dev default-libmysqlclient-dev libssl-dev \
            nodejs pkg-config python-dev python-pip rsync ruby-dev \
            dh-autoreconf libcurl4-openssl-dev libberkeleydb-perl \
            cpanminus
          sudo apt-get clean
          ## perl deps
          cpanm -i HTML::Strip::Whitespace
          perl -MCPAN -e 'install BDB'
      # - name: Install BerkeleyDB.pm
      #   run: |
      #     cpanm -i BerkeleyDB
      - name: run html_opt.pl
        run: |
          echo "Optimizing..."
          .github/workflows/scripts/html_opt.pl -d . || {
              echo "Optimize failed"
              exit 1
          }
