name: perl-test

on:
  push:
    branches:
      - 'perl-test'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: html_opt-artifact
          path: .github/workflows/scripts/html_opt.pl

      - run: echo "hello" > hello.txt
      - uses: actions/upload-artifact@v2
        with:
          name: hello.txt
          path: hello.txt

  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p modules/code

      - name: Download html_opt.pl
        uses: actions/download-artifact@v2
        with:
          name: html_opt-artifact
          path: modules/code
      - run: |
          ls -al modules/code/html_opt.pl
          cat modules/code/html_opt.pl

      - name: Download html_opt.pl
        uses: actions/download-artifact@v2
        with:
          name: hello.txt
          path: modules/code
      - run: |
          cat modules/code/hello.txt
