name: perl-test

on:
  push:
    branches:
      - 'perl-test'
  workflow_dispatch:

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: Install perl dependencies for html_opt.pl
        run: |
          sudo apt-get install -y libberkeleydb-perl
          ## perl deps
          cpanm -i HTML::Strip::Whitespace
      - run: |
          echo "Optimizing..."
          .github/workflows/scripts/html_opt.pl -d . || {
              echo "Optimize failed"
              exit 1
          }
