name: short-sha

on:
  push:
  workflow_dispatch:

jobs:
  short-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
      - run: |
          echo "SHA8 is $SHA8"
          echo "job-id is #JOB_ID"
        ennv:
          JOB_ID: "job-$SHA8"
