name: zap-scan

on:
  push:
    paths:
      - .github/workflows/zap-scan.yml
      - .github/workflows/zap-rules/rules.tsv
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        id: scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.meetup.com/blog'
          rules_file_name: '.github/workflows/zap-rules/rules.tsv'

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "${{ steps.scan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `<details><summary>ZAP Scan result</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*

            </details>`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
