name: zap-scan facebook.com
on:
  push:
    paths:
      - .github/workflows/zap-scan-facebook.yml
      - .github/workflows/zap-rules/rules.tsv
  workflow_dispatch:

jobs:
  zap_scan:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.facebook.com'
          rules_file_name: '.github/workflows/zap-rules/rules.tsv'
