name: ZAP

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd && ls -l
          pip install --upgrade pip github3.py
          pip3 install --upgrade pip github3.py
      - name: run zap baseline scan
        run: zap-baseline.py -t https://selfservice-dev.pathfinder.gov.bc.ca/ -g gen.conf -r zapdevreport.html || echo 0
      - run: |
          pwd && ls -l /zap/wrk/
          cat /zap/wrk/zapdevreport.html
          apt-get update && apt-get install -q -y bsd-mailx
          echo "ZAP Scan Report" | mailx -s "ZAP Scan Report" -r "rui@meetup.com" -a /zap/wrk/zapdevreport.html rui@meetup.com
