name: zap-scan

on:
  push:
    paths:
      - .github/workflows/zap-scan.yml
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.meetup.com/blog'
          rules_file_name: '.github/workflows/zap-rules/rules.tsv'
